services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 6s # 6 seconds
      timeout: 60s
      retries: 3
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit queue_index_max_journal_entries 0"
      RABBITMQ_USER: na3Ierntb2
      RABBITMQ_PASS: 4903utnarw/gsRg;aerqw4\tyq£?Ls
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  manager:
    build:
      context: .
      dockerfile: Dockerfile.manager
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: no
    networks:
      - rabbit
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: na3Ierntb2
      RABBITMQ_PASS: 4903utnarw/gsRg;aerqw4\tyq£?Ls
    deploy:
      replicas: 1
    volumes:
      - manager_data:/usr/src/app/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: no
    networks:
      - rabbit
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: na3Ierntb2
      RABBITMQ_PASS: 4903utnarw/gsRg;aerqw4\tyq£?Ls
    deploy:
      replicas: 6

networks:
  rabbit:
    driver: bridge

volumes:
  manager_data:
  rabbitmq_data: